# Generated by Django 5.0.1 on 2026-01-20 07:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway_order_id",
                    models.CharField(
                        db_index=True,
                        help_text="Order ID dari Midtrans/Xendit",
                        max_length=100,
                        unique=True,
                        verbose_name="Order ID Gateway",
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Transaction ID dari payment gateway",
                        max_length=100,
                        verbose_name="Transaction ID Gateway",
                    ),
                ),
                (
                    "va_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Nomor Virtual Account",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VA_BCA", "Virtual Account BCA"),
                            ("VA_BNI", "Virtual Account BNI"),
                            ("VA_MANDIRI", "Virtual Account Mandiri"),
                            ("VA_BRI", "Virtual Account BRI"),
                            ("VA_PERMATA", "Virtual Account Permata"),
                        ],
                        max_length=20,
                        verbose_name="Metode Pembayaran",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dalam Rupiah",
                        max_digits=10,
                        verbose_name="Jumlah Pembayaran",
                    ),
                ),
                (
                    "admin_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Biaya Admin",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Total yang Harus Dibayar",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Menunggu Pembayaran"),
                            ("PAID", "Lunas"),
                            ("EXPIRED", "Kadaluarsa"),
                            ("FAILED", "Gagal"),
                            ("REFUNDED", "Dikembalikan"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Waktu Pembayaran"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Batas Waktu Pembayaran"
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response dari payment gateway",
                        null=True,
                        verbose_name="Response Gateway",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="registration.studentregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pembayaran",
                "verbose_name_plural": "Pembayaran",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Payment Created"),
                            ("WEBHOOK_RECEIVED", "Webhook Received"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("ERROR", "Error Occurred"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(blank=True, max_length=20)),
                ("signature_valid", models.BooleanField(blank=True, null=True)),
                (
                    "request_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw webhook/API request",
                        null=True,
                        verbose_name="Request Data",
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Response Data"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Log",
                "verbose_name_plural": "Payment Logs",
                "db_table": "payment_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_status_426d4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway_order_id"], name="payments_gateway_191166_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["va_number"], name="payments_va_numb_fd49e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentlog",
            index=models.Index(
                fields=["payment", "created_at"], name="payment_log_payment_1593bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentlog",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="payment_log_event_t_d854a0_idx",
            ),
        ),
    ]
