# Generated by Django 5.0.1 on 2026-01-20 07:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Nomor Pendaftaran",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Format: 2024/2025",
                        max_length=9,
                        verbose_name="Tahun Ajaran",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft - Belum Submit"),
                            ("SUBMITTED", "Submitted - Menunggu Pembayaran"),
                            ("PAID", "Paid - Menunggu Verifikasi"),
                            ("VERIFIED", "Verified - Diterima"),
                            ("REJECTED", "Rejected - Tidak Lolos Verifikasi"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nama Lengkap"),
                ),
                (
                    "nisn",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "NISN harus 10 digit angka"
                            )
                        ],
                        verbose_name="NISN",
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(max_length=100, verbose_name="Tempat Lahir"),
                ),
                ("birth_date", models.DateField(verbose_name="Tanggal Lahir")),
                (
                    "gender",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                        max_length=1,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                (
                    "previous_school",
                    models.CharField(max_length=255, verbose_name="Asal Sekolah"),
                ),
                (
                    "previous_school_npsn",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="NPSN Sekolah Asal"
                    ),
                ),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(verbose_name="Tahun Lulus"),
                ),
                (
                    "program_choice",
                    models.CharField(
                        choices=[("IPA", "IPA"), ("IPS", "IPS"), ("BAHASA", "Bahasa")],
                        max_length=20,
                        verbose_name="Pilihan Program",
                    ),
                ),
                ("address", models.TextField(verbose_name="Alamat Lengkap")),
                (
                    "city",
                    models.CharField(max_length=100, verbose_name="Kota/Kabupaten"),
                ),
                ("province", models.CharField(max_length=100, verbose_name="Provinsi")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=5, verbose_name="Kode Pos"),
                ),
                (
                    "parent_name",
                    models.CharField(
                        max_length=255, verbose_name="Nama Orang Tua/Wali"
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(max_length=20, verbose_name="No. HP Orang Tua"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Waktu Submit"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Waktu Verifikasi"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Catatan Verifikasi"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pendaftaran Siswa",
                "verbose_name_plural": "Pendaftaran Siswa",
                "db_table": "student_registrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("IJAZAH", "Ijazah/STTB"),
                            ("KK", "Kartu Keluarga"),
                            ("AKTA", "Akta Kelahiran"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Dokumen",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to="documents/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Nama File Asli"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="Ukuran File (bytes)"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME Type"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Sudah Diverifikasi"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Catatan Verifikasi"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="registration.studentregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumen",
                "verbose_name_plural": "Dokumen",
                "db_table": "documents",
            },
        ),
        migrations.AddIndex(
            model_name="studentregistration",
            index=models.Index(
                fields=["status", "academic_year"], name="student_reg_status_19f027_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentregistration",
            index=models.Index(
                fields=["registration_number"], name="student_reg_registr_35baed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentregistration",
            index=models.Index(fields=["nisn"], name="student_reg_nisn_88262a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="studentregistration",
            unique_together={("user", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["registration", "document_type"],
                name="documents_registr_682279_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("registration", "document_type")},
        ),
    ]
