# Generated by Django 5.0.1 on 2026-01-20 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentregistration",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentregistration",
            name="contact_email",
            field=models.EmailField(
                default="",
                help_text="Email untuk notifikasi status pendaftaran",
                max_length=255,
                verbose_name="Email Kontak",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentregistration",
            name="contact_phone",
            field=models.CharField(
                default="",
                help_text="Nomor HP yang bisa dihubungi",
                max_length=20,
                verbose_name="No. HP Kontak",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentregistration",
            name="nisn",
            field=models.CharField(
                help_text="Nomor Induk Siswa Nasional (10 digit)",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "NISN harus 10 digit angka"
                    )
                ],
                verbose_name="NISN",
            ),
        ),
        migrations.AlterField(
            model_name="studentregistration",
            name="program_choice",
            field=models.CharField(
                choices=[
                    ("PAKET_A", "Paket A (Setara SD)"),
                    ("PAKET_B", "Paket B (Setara SMP)"),
                    ("PAKET_C_IPA", "Paket C IPA (Setara SMA)"),
                    ("PAKET_C_IPS", "Paket C IPS (Setara SMA)"),
                    ("PAKET_C_BAHASA", "Paket C Bahasa (Setara SMA)"),
                ],
                max_length=20,
                verbose_name="Pilihan Program",
            ),
        ),
        migrations.AlterField(
            model_name="studentregistration",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Opsional - hanya untuk admin yang input manual",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="studentregistration",
            index=models.Index(
                fields=["contact_email"], name="student_reg_contact_c562cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentregistration",
            index=models.Index(
                fields=["contact_phone"], name="student_reg_contact_a32a4d_idx"
            ),
        ),
    ]
