# Generated by Django 5.0.1 on 2026-01-20 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_add_contact_fields_and_nullable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='nisn',
            field=models.CharField(blank=True, help_text='Nomor Induk Siswa Nasional (10 digit)', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'NISN harus 10 digit angka')], verbose_name='NISN'),
        ),
    ]
