# Generated by Django 5.0.1 on 2026-01-21 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_studentregistration_nisn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Ayah'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pekerjaan Ayah'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Ibu'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pekerjaan Ibu'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='nik',
            field=models.CharField(blank=True, help_text='Nomor Induk Kependudukan (16 digit)', max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'NIK harus 16 digit angka')], verbose_name='NIK'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('KRISTEN', 'Kristen'), ('KATOLIK', 'Katolik'), ('HINDU', 'Hindu'), ('BUDDHA', 'Buddha'), ('KONGHUCU', 'Konghucu')], max_length=20, null=True, verbose_name='Agama'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='registration_number',
            field=models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Nomor Pendaftaran'),
        ),
    ]
