# Generated by Django 5.0.1 on 2026-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_studentregistration_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('KTP', 'KTP Siswa/Orang Tua'), ('KK', 'Kartu Keluarga'), ('AKTA', 'Akta Kelahiran')], max_length=20, verbose_name='Jenis Dokumen'),
        ),
    ]
