# Generated by Django 5.0.1 on 2026-01-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='declaration_agreed',
            field=models.BooleanField(default=False, help_text='Centang jika menyetujui pernyataan', verbose_name='Persetujuan Pernyataan'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='declaration_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Persetujuan'),
        ),
    ]
