# Generated by Django 5.0.1 on 2026-01-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_studentregistration_declaration_agreed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='program_choice',
            field=models.CharField(choices=[('PAKET_A', 'Paket A (Setara SD)'), ('PAKET_B', 'Paket B (Setara SMP)'), ('PAKET_C', 'Paket C (Setara SMA)')], max_length=20, verbose_name='Pilihan Program'),
        ),
    ]
