# Generated by Django 5.0.1 on 2026-01-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_alter_studentregistration_program_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft - Belum Submit"),
                    ("SUBMITTED", "Submitted - Menunggu Pembayaran"),
                    ("PAYMENT_EXPIRED", "Payment Expired - Daftar Ulang"),
                    ("PAID", "Paid - Menunggu Verifikasi"),
                    ("VERIFIED", "Verified - Diterima"),
                    ("REJECTED", "Rejected - Tidak Lolos Verifikasi"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
